### PR TITLE
Fix bool

### PR DESCRIPTION
**Pull request by nonguyen1**
- Fix boolean attribute with `jj-input-number`
- Convert beta browsers to specific browser versions
- Fix incorrect tests for `jj-input-number`
- Add 2 more tests to `jj-input-number`
- clean up test scripts in `package.json`

### CODE REVIEW

**Comment by yiy142** [comment]
Hi,  @nonguyen1 
Just some design idea, maybe we can put the disable check inside value setter instead of putting it inside our event listener. because i not not sure if typing in input box will trigger the value change too.

**Comment by nonguyen1** [comment]
> Hi, @nonguyen1
> Just some design idea, maybe we can put the disable check inside value setter instead of putting it inside our event listener. because i not not sure if typing in input box will trigger the value change too.
> 
> eg: user try to type in box when the component is disabled

This is does sound like a better design decision. When you get a chance could you implement that into this branch?

Thanks

**Comment by fmavb** [comment]
Can we merge this?

**Comment by nonguyen1** [comment]
Yes, please do.

**Pull request merged**
