### PR TITLE
Merge all components into one single JS file

### PR DESCRIPTION
**Pull request by fmavb**
As above

### CODE REVIEW

**Comment by ShaneNielsen1234** [comment]
But why?

**Comment by fmavb** [comment]
Chris wanted to have them all in one file

**Comment by fmavb** [comment]
I'm currently removing debug statements from the switch code

**Comment by ShaneNielsen1234** [comment]
As long as the separated files still exist, I have no problem with this.

**Comment by fmavb** [comment]
@ShaneNielsen1234 They still exist

**Comment by nonguyen1** [comment]
In the minify PR I already did this. I put all the files into `jj-component.min.js`

**Comment by fmavb** [comment]
I'll kill this PR then

**Pull request closed without merging**
