### PR TITLE
Bootstrap added to the Components

### PR DESCRIPTION
**Pull request by fmavb**
- CSS variables have been created
- Tested with the variables bootstrap provides
- Documentation and unit testing still to be done

### CODE REVIEW

**Comment by fmavb** [comment]
> Could you add something to the readme about bootstrap? Maybe a picture?

I will talk to Ryan & Martina about it

**Comment by ShaneNielsen1234** [comment]
Why is this not merged/done?

**Comment by rkeng** [comment]
> Why is this not merged/done?

Good question. I wasn't sure why Sprint 2 (bootstrap stuff) hasn't been merged to master earlier. And I don't think the testing team has been able to use the new code for our components for this reason.

**Comment by ShaneNielsen1234** [comment]
I fixed the merge conflict. But please someone pull this down and make sure everything is working as expected as I am not a javascript developer. Please try to close PR's within 24 hours to prevent stale code. Thanks!

**Comment by nonguyen1** [comment]
> I fixed the merge conflict. But please someone pull this down and make sure everything is working as expected as I am not a javascript developer. Please try to close PR's within 24 hours to prevent stale code. Thanks!

**Comment by ShaneNielsen1234** [comment]
Looks like I might have broken some stuff. Or maybe it already existed.

**Comment by fmavb** [comment]
I'll take a look

**Comment by ShaneNielsen1234** [comment]
Don’t forget to run “npm run test” before pushing

**Comment by fmavb** [comment]
npm install is taking ages, I think I found the bug

**Comment by fmavb** [comment]
All set, ready to merge

**Pull request merged**
