### PR TITLE
Modified CDN links for components

### PR DESCRIPTION
**Pull request by fmavb**
Modified CDN links so that the slider works correctly

### CODE REVIEW

**Comment by Chris-Synnott** [comment]
located in ./templates/

**Comment by fmavb** [comment]
Ok thanks :-)

**Comment by ShaneNielsen1234** [comment]
Please post your code before Pr'ing

**Comment by Chris-Synnott** [comment]
So now you updated the handlebars,

Commands:https://docs.google.com/document/d/1v-MUZE5myOuHl_VGz5HnD6n1SLm11fnGQ_sRGAqmzsc/edit

**Pull request merged**
